# Generated by Django 2.2.4 on 2020-08-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksAuthorsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='placeholder notes', verbose_name=''),
            preserve_default=False,
        ),
    ]
